export const ActionTypes = {
  CHANGE_FILTER: 'CHANGE_FILTER',
  ADD_MOVIE: 'ADD_MOVIE',
  ADD_TO_STARRED: 'ADD_TO_STARRED',
  ADD_TO_WATCHLIST: 'ADD_TO_WATCHLIST',
  REMOVE_FROM_STARRED: 'REMOVE_FROM_STARRED',
  REMOVE_FROM_WATCHLIST: 'REMOVE_FROM_WATCHLIST'
}